### ISSUE TITLE
Replace "Upload" with "Select" in all web apps

### ISSUE THREAD

**Issue by niemasd** [Niema-Lab/ViralWasm-Consensus#2]
In ViralWasm-Consensus, we currently say "**Upload** Input Reads File(s)", but we should change this to "**Select** Input Reads File(s)". More generally, in all web apps, we should replace the word "Upload" with the word "Select": the word "upload" might mislead a user into thinking their files are being uploaded somewhere, even though they're just being loaded into local memory

**Comment by daniel-ji** [comment]
Fixed in cbb055!

**Comment by daniel-ji** [comment]
Fixed in cbb055c !
